### ISSUE TITLE
Loadmap to v0.1

### ISSUE THREAD

**Issue by ryota2357** [ryota2357/lico#1]
## Todo

- [x] Create CLI to compile from the program source code file and run it. (10e492d8922c06976df29035eafa11a1e520d03a)

### Lexer
- [x] String escape sequence. (6703fb119e89d69deee922da71e4d632da8a270c)
- [x] Line comment. (3156d84c73b51d1de0a344c951c5cd399ac5e80f)

### Parser
- ~~Minimal parse error handling. It uses a rough recovery strategy.~~
- [x] Add more Span to Stat/Expr AST. This is the preparation for LS, Linter, etc that uses the span for searching/walking on the AST. (7d8d8c540b901f30620f7e6e44ba5c8bc757ba65, a50f0578d5f3ebfe79b970ec31559ac11831bdd6)

### Compiler
- [x] Compile basic AST to VM code without extra. For v0.1, the Compiler cannot compile a program containing attribute statements. (85248ac950bd3009a1e3c36c259fb38209c76c2b)
- [x] Error handling for invalid operations such as break/continue outside the loop. (59889b9226ac7987a5ab5671f5e072662bc1ae92, 383608b25318ba8ac8687398287dfce158c7d031)
- [x] VM code testing. (Lexer-Parser-Compiler-VM integration test?) (e08920840cc2c5b2fdb02d92363e3a57e5be6d96)

### VM
- [x] Minimal parse error handling. VM returns `Result<Object, String>`. The `String (Err)` is not organized and is not useful for generating error messages. (9e17a4290480fdd525b4b3b26068e567f88ffde1)
- [x] Add basic operation instructions. For v0.1, some meta method (such as `__add()`) does not work. (~ d1738854b6d77d3c0c086d1466e01956d7b4b8c3)

### Document
- ~~Deploy empty content.~~

### Lexer
- Multi-line string.
- Raw string.
- Prefix (0x, 0b, 0o) of number literal.
- Delimit the number literal via `_`.

### Parser
- Use attributes for compiling.
- Basic parse error handling.
- Add more syntax.

### Compiler
- Generate warning.
- Generate debug information.
- Optimization.

### VM
- Intern string.
- Basic parse error handling.
- Import (`require()`) other code.

### Document
- Add introduction.
- Add API reference.
- Add language specification.

**Comment by ryota2357** [comment]
Tagged v0.1.0.

v0.1.0 just means "works" and does not meet the language specification and has not yet reached a usable level.


https://github.com/ryota2357/lico/releases/tag/v0.1.0
